### ISSUE TITLE
Consider renaming ContainerImageName to ContainerRepository

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#124]
The more general nomenclature for the middle part of a fully-qualified Image name (the non-registry, non-tag portion) is Repository. We should consider changing our name to align with that, so users don't have garbled terminology.

Some deeper discussion [here](https://github.com/microsoft/dotnet-blog/pull/884#discussion_r950315562).

**Comment by baronfel** [comment]
I think we pretty much _have_ to do this. Azure and AWS both use Repository as the term for 'image name', and Google Cloud does a custom thing.

**Comment by lbruun** [comment]
+1.  Good idea.

I think it can be solved by making the documentation a bit clearer.  [Documentation PR 33319](https://github.com/dotnet/docs/pull/33319) makes it a bit better, but I think something like 

"the value between the registry physical location and the `:`"  

in a fully qualified docker image name, would have made it clear to me.

**Comment by Vhab** [comment]
@baronfel: This change seems to have introduced some regression for us.

Our csproj contains this:
```
	<PropertyGroup>
		<ContainerImageName>ourcontainername</ContainerImageName>
		<ContainerImageTag>dev</ContainerImageTag>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:7.0</ContainerBaseImage>
		<PublishProfile>DefaultContainer</PublishProfile>
	</PropertyGroup>
```

This was working fine on `7.0.307`.

After upgrading to `7.0.400` we are getting:

```
C:\Program Files\dotnet\sdk\7.0.400\Containers\build\Microsoft.NET.Build.Containers.targets(73,5): warning CONTAINER003: The property 'ContainerImageName' was set but is obsolete - please use 'ContainerRepository' instead. [path/to/our/csproj.csproj]
C:\Program Files\dotnet\sdk\7.0.400\Containers\build\Microsoft.NET.Build.Containers.targets(121,31): error MSB4064: The "ContainerRepository" parameter is not supported by the "ParseContainerProperties" task loaded from assembly: Microsoft.NET.Build.Containers, Version=7.0.302.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 from the path: C:\Users\MyUserName\.nuget\packages\microsoft.net.build.containers\7.0.302\tasks\net7.0\Microsoft.NET.Build.Containers.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property. [path/to/our/csproj.csproj]
C:\Program Files\dotnet\sdk\7.0.400\Containers\build\Microsoft.NET.Build.Containers.targets(119,5): error MSB4063: The "ParseContainerProperties" task could not be initialized with its input parameters.  [path/to/our/csproj.csproj]
```

**Comment by Vhab** [comment]
You're absolutely correct. Thank you

**Comment by baronfel** [comment]
Closing as we've done this starting in 7.0.400.

**Comment by ggirard07** [comment]
Same issue here while currently using package `0.4.0`. Tried to upgrade to latest, but now I have 401 unauthorized error as my base image is in an Azure container registry. Right now I am stuck as I am no longer able to publish either with 7.0.400 SDK nor NuGet 0.4.0 nor NuGet 7.0.400 (also tried (7.0.307, same issue).
Trying to publish here right from command line with dotnet build/publish, as CI does.
@baronfel can this be reopened for investigation?

**Comment by ggirard07** [comment]
Adding the link to my developer community feedback related to my issue aforementioned for visibility purposes.
https://developercommunity.visualstudio.com/t/Response-status-code-does-not-indicate/10446987

**Comment by hotfix-houdini** [comment]
@ggirard07 fwiw, if you're logging into azure with a service principal or managed identity before your `az acr login -n myacr`, then you would get a 401 unauthorized on the dotnet publish due to https://github.com/dotnet/sdk-container-builds/issues/425. 

https://github.com/hotfix-houdini/bug-dotnet-publish-containerize-docker-auth/blob/main/README.md (scroll down nearly to the bottom) has some shell to hack your docker.config to get the dotnet publish to work before PR #425 makes it to production. I've used it several different times. Hope that's what you're running into.

**Comment by baronfel** [comment]
Hi @ggirard07 - based on your binlog (and what you mentioned in the feedback ticket) I'm going to agree with @hotfix-houdini here - this currently won't work because we don't support IdentityToken based authentication in this tooling. This will be fixed when .NET 8 RC1 releases in a couple weeks, but until then you'll have to use the workarounds that @hotfix-houdini has in their repo. Alternatively, you can use the admin credentials for your ACR to login and authenticate, which has been supported since the start of this tooling.

**Comment by ggirard07** [comment]
Just a note here to be sure we are speaking about the same stuff: what is not working is pulling the base image mentioned in `ContainerBaseImage`, not pushing the published/built image to ACR. In our case, we publish/push to local daemon with dotnet publish, then relies on  ADO pipeline with Docker@2 task to push to ACR.
We have been using it through `az acr login` and RBAC assigned with `AcrPull` for service principal for quiet some time in our CI and NuGet `0.4.0` (at least beginning of May). Since `7.0.400` has been deployed to Azure DevOps hosted agents, we are no longer able to publish, so deploy in our dev/qa/prod environment any services anymore. If it is not a breaking change, then definitively it was working by miracle before. Now we are stuck with pipeline no longer able to deploy our services anymore...
It was also working properly locally with my own identity at that time. Same NuGet, 0.4.0, and whatever SDK was shipped with Visual Studio 17.6 (I assume not 7.0.400...).

I will take a look in the workaround mentioned in linked issue just in case it also solves mine and report back.

**Comment by baronfel** [comment]
The authentication mechanism is the same for both pulling and pushing - so I'd have expected it to fail in all scenarios.

**Comment by ggirard07** [comment]
Just a note here that I can confirm it is now working again in our pipeline. In this case we were only impacted by the issue of removing the NuGet package but not the authentication issue. I think this is because we rely on `Docker@2`  task with an ARM service connection to authenticate instead of `az acr login`. I pulled the config.json file from agent once authenticated with `Docker@2`, and in this case it looks like token provider is not used, but auth+email is used instead:
```json
{
    "auths": {
        "myacr.azurecr.io": {
            "auth": "secret obfuscated",
            "email": "ServicePrincipal@AzureRM"
        }
    },
    "HttpHeaders": {
        "X-Meta-Source-Client": "VSTS"
    }
}
```

For the local usage with `az acr login`, my only guess is that I was mistaken during my dev and was relying on public images at that time only. Once I moved to base image in our ACR, I assume I only used it from pipeline since that time...
