### ISSUE TITLE
Lacking msbuild.exe coverage in testing scenarios

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/sdk-container-builds#173]
We don't have test coverage for the net472 scenario in our testing.

- [ ] Create a windows leg for CI
- [ ] Ensure msbuild is installed on it
- [ ] Create/duplicate/modify `EndToEnd_NoAPI` for the net472 scenario (should just need to change the actual publish command args)

The command line I use to run the net472 scenario: 

```
msbuild /t:Publish /p:RuntimeIdentifier=linux-x64 /p:Configuration=Release /p:PublishProfile=DefaultContainer
```

**Comment by baronfel** [comment]
It's going to be hard to test the actual push to `docker` daemons here - the Windows Github Actions runners don't have Docker installed due to licensing. We could probably mark tests with a trait for those that require a running Registry and don't enable them in CI to at least get partial coverage on Windows.  We have similar problems on macOS.

**Comment by baronfel** [comment]
This was done in #349
