### ISSUE TITLE
.NET 8 preview 6 containers do not run as app user

### ISSUE THREAD

**Issue by wazzamatazz** [dotnet/sdk-container-builds#479]
I have an ASP.NET Core application targeting .NET 8 with a container image built using the `DefaultContainer` profile.

Since updating to preview 6 of the SDK I've noticed that the application no longer runs as the app user. I initially thought that it was an [issue with the base image](https://github.com/dotnet/dotnet-docker/issues/4766) but I've found that I can only replicate it when building the container image using the SDK publish profile.

I think it's related to [this change](https://github.com/dotnet/dotnet-docker/pull/4715) to the app user UID in the base image as there is still an [open issue here](https://github.com/dotnet/sdk-container-builds/issues/395) about the UID being hard-coded in places instead of using the `APP_UID` variable.

The workaround is to explicity run the container as UID 1654.

**Comment by baronfel** [comment]
More broadly we need to do processing of environment variables during image construction and programmatically set the user if we see the new environment variables, instead of hard coding it as we do now
This is similar to what we need to do for ASPNETCORE_URLS and Container ports, which I wrote up yesterday.
