### ISSUE TITLE
Support publishing multiarch containers

### ISSUE THREAD

**Issue by wasabii** [dotnet/sdk-container-builds#514]
Right now I build my containers by using MSBuild to publish multiple RIDs of my application to directories.

I then manually use docker compose to assemble the docker images.

I then use docker manifest create to create a multiarch container from the multiple images. The multiarch image is what gets published.

It would be neat if the Publish targets could do this. It would have to be a new OuterBuild-like thing though, invoking publish multiple times with differnet RuntimeIdentifier set, etc.

**Comment by baronfel** [comment]
Related to https://github.com/dotnet/sdk-container-builds/issues/87 I believe.

Yes this is a good thing to add, but there are UX concerns - for example currently docker manifest lists can only take inputs that are pushed to an actual container registry, so we'd need validation there. We'd also need to add support for the docker manifest primitives to the library portion of the container tools.

Not a blocker, it just needs design - especially because multi-rid publish isn't really something we do in many other parts of the platform (except maybe MAUI).

**Comment by wasabii** [comment]
Ahh. I did a search for issues, but did not see that one. Lack of the word 'arch' in the subjects, I guess. This does appear to be covered by #87.
